on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        # Should go down to lowest non-EOL version
        # https://www.ruby-lang.org/en/downloads/branches/
        ruby: [2.5, 2.6, 2.7]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - run: bundle install --jobs 4 --retry 3
      - run: bundle exec rake
